console.log('!----------!')
console.log('!----------!')
console.log("1. SUCCESS")
console.log("2. FAIL")
console.log("3. SUCCESS")
console.log("4. PASS")
console.log('!----------!')
console.log('!----------!')
